project:
  type: website

website:
  title: "Floral continuity"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: firstlook.qmd
        text: First Look
      - href: Landscape projection.qmd
        text: project-flowers.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
