project:
  type: website
  output-dir: docs
  render:
  - "*.qmd"
  - "!data-raw/"

website:
  title: "Floral continuity"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: firstlook.qmd
        text: First Look
      - href: project-flowers.qmd
        text: Landscape projection

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
